### ISSUE TITLE
iOS Crashed

### ISSUE THREAD

**Issue by kleinandreas** [thedoritos/unimgpicker#1]
After compiling the Samples project. It runs on iPhone 6 Plus but if you click on the button. You get an error: 

'NSInvalidArgumentException', reason: '-[Picker show:outputFileName:]: unrecognized selector sent to instance 0x1702356a0'
*** First throw call stack:
(0x1886211b8 0x18705855c 0x188628268 0x188625270 0x18851e80c 0x10043a7e8 0x1000f2184 0x1002472b8 0x1003ce368 0x100203570 0x10020311c 0x100202ab8 0x100417968 0x100beeb50 0x10067d98c 0x100747c3c 0x100537224 0x100624b70 0x10079e214 0x1000debc4 0x1000deac0 0x18b876f24 0x18b876dd0 0x18888e094 0x1885b6e50 0x1885cf218 0x1885ce9cc 0x1885cc4b0 0x1884fa2b8 0x189fae198 0x18e5417fc 0x18e53c534 0x1000d8a3c 0x1874dd5b8)
libc++abi.dylib: terminating with uncaught exception of type NSException(lldb) 

and the app crashed.

If you look into the Plugin folder you get an Warning on line 23: @implementation Picker with this warning:
Libraries/Plugins/iOS/Unimgpicker/Picker.mm:23:17: Method definition for 'show:outputFileName:' not found

**Comment by thedoritos** [comment]
Hi, @kleinandreas 

Thanks for reporting the issue.

I fixed the problem and pushed a new package (v1.1.1).
I tested it on my environment and it seems to work.

Could you try it?

**Comment by kiroskirin** [comment]
@thedoritos The issue occur with **Picker.mm** file that you call function

`[picker show:[NSString stringWithUTF8String:title] outputFileName:[NSString stringWithUTF8String:outputFileName]];`

instead of

`[picker show:[NSString stringWithUTF8String:title] outputFileName:[NSString stringWithUTF8String:outputFileName] maxSize:maxSize];`

also **Picker.h** should define 

`- (void)show:(NSString *)title outputFileName:(NSString *)name maxSize:(NSInteger)maxSize;`

**Comment by thedoritos** [comment]
@kiroskirin Thanks for the information.

Yes, you are right! And I've made the exactly same change on ecf89dac3d5210294f920b9bcf10b5abc8681820

The code on the branch `fix/ios_crash_on_select_image` is fixed as well as the pacakge `v1.1.1`.

**Comment by kiroskirin** [comment]
@thedoritos It work but can you merge to master branch?

**Comment by thedoritos** [comment]
@kleinandreas @kiroskirin I'll merge it and close this issue.

Thank you.
