### ISSUE TITLE
Find real image Path in android & IOS

### ISSUE THREAD

**Issue by EngKareemHesham** [thedoritos/unimgpicker#13]
Hello,
I found the asset you shared amazing and used it with no bugs at all.
The only problem I found is not getting the real path of the image as I am using an Exif viewer which requires the real image's path to read it from.
Is there a way to find it?

**Comment by thedoritos** [comment]
Hi, @EngKareemHesham ! Thx for your interest.

> Is there a way to find it?

No. I believe it's not possible to get the REAL path in iOS/Android environment due to security issues.
Unimgpicker uses image pickers provided by iOS/Android SDK, and the picked image path is abstracted. Even if you passed back the path to Unity's world, you'll not be able to read the image from it.

If you want to read Exif info, you have to modify the native plugins.

- iOS: https://github.com/thedoritos/unimgpicker/blob/master/Assets/Plugins/iOS/Unimgpicker/Picker.mm#L54-L92
- Android: https://github.com/thedoritos/unimgpicker/blob/master/unimgpicker_android/unimgpicker/src/main/java/com/kakeragames/unimgpicker/Picker.java#L73-L136

I'm sorry I could not provide a good answer :(

Thank you.

**Comment by EngKareemHesham** [comment]
Actually it did help a lot.
This is the line I should edit in android :
File output = context.getFileStreamPath(mOutputFileName); to
File output = context.getFileStreamPath(uri); I will try it and if it worked I will upload to your github,Thanks a lot
________________________________

**Comment by thedoritos** [comment]
I'm grad if you can send me a pull request!

Thank you :)

**Comment by EngKareemHesham** [comment]
Hello,
I am sorry I don't use github this much thus I never used the pull request.
Anyway to help you making the script better this is what I made to solve my problem :
In the picker.java :

Uri uri = data.getData();


RealPath = getRealPathFromURI(uri);

This helped me convert your uri and getting the real path


public String getRealPathFromURI (Uri contentUri) {
    String path = null;
    String[] proj = { MediaStore.MediaColumns.DATA };
    Cursor cursor = getActivity().getContentResolver().query(contentUri, proj, null, null, null);
    if (cursor.moveToFirst()) {
        int column_index = cursor.getColumnIndexOrThrow(MediaStore.MediaColumns.DATA);
        path = cursor.getString(column_index);
    }
    cursor.close();
    return path;
}


Also I had a big problem for days because the android source file didn't have the unity classes.jar Just putting in there solved the problem :
"unimgpicker_android\unimgpicker\Applications\Unity\PlaybackEngines\AndroidPlayer\Variations\il2cpp\Release\Classes\classes.jar"


Hope I had helped you like you helped me ^_^
If you need anything don't hesitate to ask
Kareem Hesham

________________________________

**Comment by EngKareemHesham** [comment]
Hi again,
Here is a working version I finished today with unity and all ,You can check if it helps you as well
https://www.dropbox.com/s/f757rol7kzd17b4/unimgpicker-master%20-%20final%20with%20unity.rar?dl=0
________________________________
