### ISSUE TITLE
Return path of any file

### ISSUE THREAD

**Issue by waqashaxhmi143** [thedoritos/unimgpicker#6]
Can you make it like we can select any type of file and then handle it in unity itself.

Can you modify it for Android and IOS both ??

Thanks in advance

**Comment by thedoritos** [comment]
Hi, @waqashaxhmi143 

Your proposal is interesting but I think it's a little difficult.

- For Android, it's possible by sending Intent without filter `image/*`.
- For iOS, it's not possible because Unimgpicker depends on `UIImagePickerController`.

We need significant amount of changes. That should be an another library.

Thank you.
